[%
    T = {
        configure_1                                = "IntranetUserJS: HoldID Configuration",
        configure_2                                = "Home",
        configure_3                                = "Plugins",
        configure_4                                = "&rsaquo; IntranetUserJS: HoldID &rsaquo; Configuration",
        configure_5                                = "Report ID to use",
        configure_6                                = "Save configuration",
        configure_7                                = "Upgrade status",
        configure_8                                = "Plugin has never been upgraded.",
        viewjs_1                                   = "IntranetUserJS: HoldID",
        viewjs_2                                   = "&rsaquo; Holdid &rsaquo; View JS Tool",
    }
%]
