[%
    T = {
        configure_1                                = "IntranetUserJS: Hold ID",
        configure_2                                = "Home",
        configure_3                                = "Plugins",
        viewjs_1                                   = "IntranetUserJS: Hold ID",
        viewjs_2                                   = "&rsaquo; Hold ID &rsaquo; View JS plugin",
    }
%]
