[%
    T = {
        configure_1                                = "IntranetUserJS: Varaustunnus",
        configure_2                                = "Etusivu",
        configure_3                                = "Liitännäiset",
        viewjs_1                                   = "IntranetUserJS: Varaustunnus",
        viewjs_2                                   = "&rsaquo; Varaustunnus &rsaquo; Näytä JS-liitännäinen",
    }
%]