[%
    T = {
        configure_1                                = "IntranetUserJS: Reservationskod",
        configure_2                                = "Hem",
        configure_3                                = "Plugins",
        viewjs_1                                   = "IntranetUserJS: Reservationskod",
        viewjs_2                                   = "&rsaquo; Reservationskod &rsaquo; Visa JS-plugin",
    }
%]